### ISSUE TITLE
Port Radar Chart to Hero Hub

### ISSUE THREAD

**Issue by Levvine** [revaturelabs/TrialoftheTitans#412]
- [x] Set up experience cloud to view existing progress
- [x] Examine code for existing D3 component references
- [x] Update existing component
- [x] Write controller to retrieve exam scores
 - Import Data
 - Display Data

**Comment by Levvine** [comment]
Comment
